# Generated by Django 4.1 on 2022-08-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40, verbose_name='Имя пользователя')),
                ('mail', models.CharField(max_length=100, verbose_name='Почта пользователя')),
            ],
        ),
    ]
